### ISSUE TITLE
Duplicated nullifiers

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#49] opened 2023-10-25 15:42 UTC
This issue is coming from the points in this comment: https://github.com/0xPolygonMiden/miden-node/issues/43#issuecomment-1777220589

The observations are:

- nullifiers are not enforced by the protocol to be unique, i.e. it is possible to construct notes with the same nullifier if tokens are burned
- the primary means to synchronize with the rollup and get updates, including for nullifiers, is to use the state sync endpoint
- it is possible for an attacker to produce a note `n1` with nullifier `l`, then some time later produce another note `n2` with the same nullifier `l`. Clients can learn about the note `n2`, verify there is no nullifier `l` produced after `n2`, and try to consume that note. This won't work because `n1` has been consumed already, and the same nullifier has been produced

**Comment by hackaugusto** [comment] 2023-10-25 15:48
Two proposed solutions:

- add another endpoint to fetch nullifiers from any tree verified by the transaction kernel. this endpoint would be time independent, so it would include the nullifier `l` produce by consuming the node `n1`.
- change the nullifier scheme so that an attacker can not control the nullifier. This could be done by using different slices of a XOF function. Introducing some random element to the nullifier's hash that is out of control from the attacker (this could also be done by changing the nullifier from a hash to another construction, perhaps every note would have an associated ephemeral key and the nullifier is a signature from said key).

**Comment by bobbinth** [comment] 2023-10-25 20:33
One observation: for public notes there could be a mitigation mechanism at the node level. Specifically, nodes would know if a given note has a duplicate nullifier and could take various actions based on that. For example:

- A node could discard any transaction which outputs a public note with a duplicate nullifier (probably not a good idea).
- A node could send info to the client on whether a given public note already has a nullifier together with the note info (i.e., when it is downloaded for the first time).

These, of course, don't solve the issue with private/encrypted notes as the nodes won't be able to compute nullifiers for these - so, a separate endpoint will still probably be required to address these.

**Comment by hackaugusto** [comment] 2024-01-24 16:57
We now have an endpoint to list the nullifiers:

https://github.com/0xPolygonMiden/miden-node/blob/58be2733cae265c8937391acc72cdc52d98af117/proto/proto/store.proto#L17

If we add filtering to the request, it would be sufficient to fix this issue.

**Comment by bobbinth** [comment] 2024-01-24 17:54
`ListNullifiers` was intended primarily for internal testing (and so we didn't expose it via RPC). If we are to make it public, we should also add pagination and maybe other things.

**Comment by bobbinth** [comment] 2024-08-27 21:47
Closing as we now have `CheckNullifiersByPrefix` endpoint (implemented in https://github.com/0xPolygonMiden/miden-node/pull/419).

**Closed by bobbinth** 2024-08-27 21:47 UTC
