### ISSUE TITLE
[Feature]: Improve implementation of `get_state_sync` removing details

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#309] opened 2024-04-10 07:39 UTC
### To whom is this feature for?

End user

### Why is is this feature needed?

To reduce the amount of computation made by `get_state_sync`

https://github.com/0xPolygonMiden/miden-node/blob/3c8ba1263df5343848294cde6099a29ca6ba7996/store/src/db/sql.rs#L629

### How is this feature used?

As of now the sql queries done on the `store` database for `get_state_sync` requires us to make another query with is `select_notes_since_block_by_tag_and_sender` to get notes. 

We want to remove details from this query to be able to not have to make a high amount of work. If needed the user will make a subsequent query to `get_notes_by_id` to query on-chain note details.

### Anything else?

https://github.com/0xPolygonMiden/miden-node/pull/300#discussion_r1554842395

**Comment by Dominik1999** [comment] 2024-05-13 12:59
Would a user be able to get a note by its ID? The issue is not super clear to me

**Comment by bobbinth** [comment] 2024-05-13 20:02
The user should already be able to do that. This issue is of an optimization issue for how things are handled internally (currently, we do more work than needed in some situations).

**Comment by polydez** [comment] 2024-08-30 10:37
Resolved by https://github.com/0xPolygonMiden/miden-node/pull/462

**Closed by polydez** 2024-08-30 10:37 UTC
Labels: enhancement
